FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache aws-cli

ENV AWS_DEFAULT_REGION=us-east-1
ENV AWS_ACCESS_KEY_ID=x
ENV AWS_SECRET_ACCESS_KEY=x

COPY entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]


